# Generated by Django 6.1 on 2026-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='Nhập tên', max_length=50)),
                ('ki_hieu', models.CharField(default='Nhập kí hiệu', max_length=5)),
                ('STT', models.PositiveIntegerField(unique=True)),
                ('khoi_luong', models.FloatField()),
                ('cau_hinh', models.CharField(default='Nhập cấu hình electron', max_length=50)),
                ('do_am_dien', models.FloatField()),
                ('oxi_hoa', models.CharField()),
            ],
        ),
    ]
